### ISSUE TITLE
can this be used with URLs?

### ISSUE THREAD

**Issue by NullVoxPopuli** [lifegadget/ui-download#1]
rather than putting the whole file in the data attribute?

**Comment by yankeeinlondon** [comment]
Hmmm. Can you elaborate a little more on what your trying to achieve?

**Comment by NullVoxPopuli** [comment]
well, based on the examples,

```
{{ui-download
  mime='text/xml'
  data=xmlData
  filename='foobar.xml'
  text='download!'
}}
```

it looks like what is downloaded is what the value of `data` is. 

I wonder if there is a way to make a call to the server to retrieve a file instead of downloading from data on the `data` attribute? (and also so large files don't get inserted into the dom)

**Comment by yankeeinlondon** [comment]
Well the primary goal of this add on was to do client-side downloads. Server side downloads are more common but there are use cases for both.

**Comment by NullVoxPopuli** [comment]
I'm primarily looking for a way to be able start a download from the server in js, so I can handle errors, if any.

**Comment by yankeeinlondon** [comment]
Makes sense. This addon is probably not the best fit for that. I'm going to close this for now. If you feel it should be open though please do re-open.
